import Head from "next/head";

const Meta = ({ title, keywords, description}) => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content={keywords}/>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
        <title>{`WebDev News | ${title}`}</title>
      </Head>
    </div>
  )
}

Meta.defaultProps = {
  title: "",
  keywords: "Web development, programming",
  description: "Get the latest news in web dev"
}

export default Meta
